// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package messaging is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Msg
*/
package messaging

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	Match   string `protobuf:"bytes,1,opt,name=match" json:"match,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Handle  []byte `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Flags   int32  `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	Hash    []byte `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Msg) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *Msg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Msg) GetHandle() []byte {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *Msg) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Msg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg)(nil), "messaging.msg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0xcf, 0xcc, 0x4b,
	0x57, 0x2a, 0xe7, 0x62, 0xce, 0x2d, 0x4e, 0x17, 0x12, 0xe1, 0x62, 0xcd, 0x4d, 0x2c, 0x49, 0xce,
	0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x24, 0xb8, 0xd8, 0x0b, 0x12, 0x2b,
	0x73, 0xf2, 0x13, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x31, 0x2e,
	0xb6, 0x8c, 0xc4, 0xbc, 0x94, 0x9c, 0x54, 0x09, 0x66, 0xb0, 0x04, 0x94, 0x07, 0x32, 0x27, 0x2d,
	0x27, 0x31, 0xbd, 0x58, 0x82, 0x45, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc2, 0x11, 0x12, 0xe2, 0x62,
	0xc9, 0x48, 0x2c, 0xce, 0x90, 0x60, 0x05, 0xab, 0x05, 0xb3, 0x93, 0xd8, 0xc0, 0x4e, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x14, 0x29, 0xc7, 0xd7, 0x97, 0x00, 0x00, 0x00,
}
